version: '3.8'

services:

  sqlserver:  # Define the SQL Server 
    build:
      context: ./sqlSetup
      dockerfile: sql.Dockerfile
    container_name: sqlserver
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - sipcart_net 

  sipcart:  # Define the main service
    build:
      context: .
      dockerfile: app.Dockerfile
      target: final
    image: sipcart-image
    container_name: sipcart
    ports:
      - "44358:8080"
    networks:
      - sipcart_net  

  tests:  # Define the tests
    container_name: tests
    build:
      context: .
      dockerfile: app.Dockerfile
      target: tests
    image: testingapp-image
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
  sipcart_net:  # Define the custom network
    driver: bridge